version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: imei_checker_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - imei_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: imei_checker_bot
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - imei_network

networks:
  imei_network:
    driver: bridge
